id: P010534
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16579
  title: གནའ་བོའི་རྒྱ་གར་ཤེས་རིག་དང་བོད་བརྒྱུད་གྲུབ་མཐའི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    89f844e7aa9148079d6a5ebcd8b3435b:
      image_group_id: I2PD18675
      title: ''
      volume_number: 1
      total_pages: 329
      base_file: v001.txt
